# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1af4d52a15d84b032250a37b341a2bcb32506a97c668d0e6afdfc12106bfe08e597cc59902cc08429ef0ab83d951e02e75edeebd46074c8098c072abf14d062

test:
  secret_key_base: 7be7693f7e3c96df64cfd30ea9fd8453c22269a53bdd7cedac1cc3c41932750581f753692af85784adb85827f201ff4dd764a42c565a1f7d507d27fd3043d595

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
